export const SKILL = [
  {
    id: 2,
    name: 'PHP',
    slug: 'php',
  },
  {
    id: 4,
    name: 'NodeJS',
    slug: 'nodejs',
  },
  {
    id: 5,
    name: 'ASP.NET',
    slug: 'aspnet',
  },
  {
    id: 6,
    name: 'iOS',
    slug: 'ios',
  },
  {
    id: 7,
    name: 'Mobile Apps',
    slug: 'mobile-apps',
  },
  {
    id: 8,
    name: 'C++',
    slug: 'cpp',
  },
  {
    id: 9,
    name: 'Android',
    slug: 'android',
  },
  {
    id: 10,
    name: 'Laravel',
    slug: 'laravel',
  },
  {
    id: 11,
    name: 'Codeigniter',
    slug: 'codeigniter',
  },
  {
    id: 12,
    name: 'CakePHP',
    slug: 'cakephp',
  },
  {
    id: 13,
    name: 'Symfony',
    slug: 'symfony',
  },
  {
    id: 14,
    name: 'Java',
    slug: 'java',
  },
  {
    id: 15,
    name: '.NET',
    slug: 'net',
  },
  {
    id: 16,
    name: 'AngularJS',
    slug: 'angularjs',
  },
  {
    id: 17,
    name: 'Bridge Engineer',
    slug: 'bridge-engineer',
  },
  {
    id: 18,
    name: 'C#',
    slug: 'csharp',
  },
  {
    id: 19,
    name: 'Embedded',
    slug: 'embedded',
  },
  {
    id: 20,
    name: 'HTML5',
    slug: 'html5',
  },
  {
    id: 21,
    name: 'Objective C',
    slug: 'objective-c',
  },
  {
    id: 22,
    name: 'JQuery',
    slug: 'jquery',
  },
  {
    id: 23,
    name: 'Ruby on Rails',
    slug: 'ruby-on-rails',
  },
  {
    id: 24,
    name: 'Unity',
    slug: 'unity',
  },
  {
    id: 25,
    name: 'Oracle',
    slug: 'oracle',
  },
  {
    id: 26,
    name: 'PostgreSql',
    slug: 'postgresql',
  },
  {
    id: 27,
    name: 'ReactJS',
    slug: 'reactjs',
  },
  {
    id: 28,
    name: 'Python',
    slug: 'python',
  },
  {
    id: 29,
    name: 'XML',
    slug: 'xml',
  },
  {
    id: 32,
    name: 'Yii2',
    slug: 'yii2',
  },
  {
    id: 33,
    name: 'Security',
    slug: 'security',
  },
  {
    id: 35,
    name: 'IT Support / Networking',
    slug: 'it-support-networking',
  },
  {
    id: 36,
    name: 'Database',
    slug: 'database',
  },
  {
    id: 37,
    name: 'Thiết kế hệ thống',
    slug: 'thiet-ke-he-thong',
  },
  {
    id: 38,
    name: 'QA',
    slug: 'qa',
  },
  {
    id: 39,
    name: 'QC',
    slug: 'qc',
  },
  {
    id: 40,
    name: 'Tester',
    slug: 'tester',
  },
  {
    id: 41,
    name: 'TeamLead',
    slug: 'teamlead',
  },
  {
    id: 42,
    name: 'Project Manager',
    slug: 'project-manager',
  },
  {
    id: 43,
    name: 'CSS3',
    slug: 'css3',
  },
  {
    id: 44,
    name: 'Javascript',
    slug: 'javascript',
  },
  {
    id: 45,
    name: 'Trưởng phòng IT',
    slug: 'truong-phong-it',
  },
  {
    id: 46,
    name: 'Nhân viên SEO',
    slug: 'nhan-vien-seo',
  },
  {
    id: 47,
    name: 'Thiết kế đồ họa',
    slug: 'thiet-ke-do-hoa',
  },
  {
    id: 48,
    name: 'Blockchain',
    slug: 'blockchain',
  },
  {
    id: 49,
    name: 'Kĩ sư điện tự động hóa',
    slug: 'ki-su-dien-tu-dong-hoa',
  },
  {
    id: 50,
    name: 'Comtor',
    slug: 'comtor',
  },
  {
    id: 51,
    name: 'Business Analyst',
    slug: 'business-analyst',
  },
  {
    id: 52,
    name: 'HR',
    slug: 'hr',
  },
  {
    id: 53,
    name: 'Admin IT',
    slug: 'admin-it',
  },
  {
    id: 54,
    name: 'Sale Man',
    slug: 'sale-man',
  },
  {
    id: 55,
    name: 'AI Engineer',
    slug: 'ai-engineer',
  },
  {
    id: 56,
    name: 'ABAP',
    slug: 'abap',
  },
  {
    id: 57,
    name: 'Telesale',
    slug: 'telesale',
  },
  {
    id: 58,
    name: 'React Native',
    slug: 'react-native',
  },
  {
    id: 59,
    name: 'UI/UX',
    slug: 'uiux',
  },
  {
    id: 60,
    name: 'Product Manager',
    slug: 'product-manager',
  },
  {
    id: 62,
    name: 'Ruby',
    slug: 'ruby',
  },
  {
    id: 63,
    name: 'VueJS',
    slug: 'vuejs',
  },
  {
    id: 64,
    name: 'Flutter',
    slug: 'flutter',
  },
  {
    id: 65,
    name: 'DevOps',
    slug: 'devops',
  },
  {
    id: 66,
    name: 'Golang',
    slug: 'golang',
  },
  {
    id: 67,
    name: 'AI',
    slug: 'ai',
  },
  {
    id: 68,
    name: 'Game',
    slug: 'game',
  },
  {
    id: 69,
    name: 'Human Resource',
    slug: 'human-resource',
  },
  {
    id: 70,
    name: 'System Admin',
    slug: 'system-admin',
  },
  {
    id: 71,
    name: 'Product Owner',
    slug: 'product-owner',
  },
  {
    id: 72,
    name: 'Marketing',
    slug: 'marketing',
  },
  {
    id: 73,
    name: 'Magento',
    slug: 'magento',
  },
  {
    id: 74,
    name: 'Photoshop/AI',
    slug: 'photoshopai',
  },
  {
    id: 75,
    name: 'Graphic Design',
    slug: 'graphic-design',
  },
  {
    id: 76,
    name: 'Kotlin',
    slug: 'kotlin',
  },
  {
    id: 77,
    name: 'Swift',
    slug: 'swift',
  },
  {
    id: 78,
    name: 'Solution Engineer',
    slug: 'solution-engineer',
  },
  {
    id: 79,
    name: 'NestJs',
    slug: 'nestjs',
  },
  {
    id: 80,
    name: 'Express',
    slug: 'express',
  },
  {
    id: 81,
    name: 'System Engineer',
    slug: 'system-engineer',
  },
  {
    id: 82,
    name: 'Azure',
    slug: 'azure',
  },
  {
    id: 83,
    name: 'Scrum Master',
    slug: 'scrum-master',
  },
  {
    id: 84,
    name: 'Software Architecture',
    slug: 'software-architecture',
  },
  {
    id: 86,
    name: 'Product Executive',
    slug: 'product-executive',
  },
  {
    id: 87,
    name: 'Giám sát dự án',
    slug: 'giam-sat-du-an',
  },
  {
    id: 88,
    name: 'AWS',
    slug: 'aws',
  },
  {
    id: 89,
    name: 'CTO',
    slug: 'cto',
  },
  {
    id: 90,
    name: 'Data Mining',
    slug: 'data-mining',
  },
  {
    id: 91,
    name: 'CIO',
    slug: 'cio',
  },
  {
    id: 92,
    name: 'COO',
    slug: 'coo',
  },
  {
    id: 93,
    name: 'Salesforce',
    slug: 'salesforce',
  },
  {
    id: 94,
    name: 'Database Adminnistrator',
    slug: 'database-adminnistrator',
  },
  {
    id: 95,
    name: 'Sales Director',
    slug: 'sales-director',
  },
  {
    id: 96,
    name: 'Docker',
    slug: 'docker',
  },
  {
    id: 97,
    name: 'CI/CD Tools',
    slug: 'cicd-tools',
  },
  {
    id: 98,
    name: 'Hasura GraphQL',
    slug: 'hasura-graphql',
  },
  {
    id: 99,
    name: 'Technical Manager',
    slug: 'technical-manager',
  },
  {
    id: 100,
    name: 'Remote',
    slug: 'remote',
  },
]

export const LOCATION = [
{
    id: 11,  
    name: 'Hà Nội',
    slug: 'ha-noi',
    type: 'thanh-pho',
    name_with_type: 'Thành phố Hà Nội',
    code: '1',
  },
  {
    id: 12,
    name: 'Hồ Chí Minh',
    slug: 'ho-chi-minh',
    type: 'thanh-pho',
    name_with_type: 'Thành phố Hồ Chí Minh',
    code: '79',
  },
  {
    id: 13,
    name: 'Vĩnh Phúc',
    slug: 'vinh-phuc',
    type: 'tinh',
    name_with_type: 'Tỉnh Vĩnh Phúc',
    code: '26',
  },
  { 
    id: 14,
    name: 'Ninh Bình',
    slug: 'ninh-binh',
    type: 'tinh',
    name_with_type: 'Tỉnh Ninh Bình',
    code: '37',
  },
  { 
    id: 15,
    name: 'Cà Mau',
    slug: 'ca-mau',
    type: 'tinh',
    name_with_type: 'Tỉnh Cà Mau',
    code: '96',
  },
  { 
    id: 16,
    name: 'Nghệ An',
    slug: 'nghe-an',
    type: 'tinh',
    name_with_type: 'Tỉnh Nghệ An',
    code: '40',
  },
  { 
    id: 17,
    name: 'Vĩnh Long',
    slug: 'vinh-long',
    type: 'tinh',
    name_with_type: 'Tỉnh Vĩnh Long',
    code: '86',
  },
  { 
    id: 18,
    name: 'Quảng Bình',
    slug: 'quang-binh',
    type: 'tinh',
    name_with_type: 'Tỉnh Quảng Bình',
    code: '44',
  },
  { 
    id: 19,
    name: 'Hải Phòng',
    slug: 'hai-phong',
    type: 'thanh-pho',
    name_with_type: 'Thành phố Hải Phòng',
    code: '31',
  },

  { 
    id: 20,
    name: 'Đồng Tháp',
    slug: 'dong-thap',
    type: 'tinh',
    name_with_type: 'Tỉnh Đồng Tháp',
    code: '87',
  },
  { 
    id: 21,
    name: 'Lai Châu',
    slug: 'lai-chau',
    type: 'tinh',
    name_with_type: 'Tỉnh Lai Châu',
    code: '12',
  },
  { 
    id: 22,
    name: 'Hưng Yên',
    slug: 'hung-yen',
    type: 'tinh',
    name_with_type: 'Tỉnh Hưng Yên',
    code: '33',
  },
  { 
    id: 23,
    name: 'Lạng Sơn',
    slug: 'lang-son',
    type: 'tinh',
    name_with_type: 'Tỉnh Lạng Sơn',
    code: '20',
  },
  { 
    id: 24,
    name: 'Đồng Nai',
    slug: 'dong-nai',
    type: 'tinh',
    name_with_type: 'Tỉnh Đồng Nai',
    code: '75',
  },
  { 
    id: 25,
    name: 'Tiền Giang',
    slug: 'tien-giang',
    type: 'tinh',
    name_with_type: 'Tỉnh Tiền Giang',
    code: '82',
  },
  { 
    id: 26,
    name: 'Phú Yên',
    slug: 'phu-yen',
    type: 'tinh',
    name_with_type: 'Tỉnh Phú Yên',
    code: '54',
  },
  { 
    id: 27,
    name: 'Yên Bái',
    slug: 'yen-bai',
    type: 'tinh',
    name_with_type: 'Tỉnh Yên Bái',
    code: '15',
  },
  { 
    id: 28,
    name: 'Bình Dương',
    slug: 'binh-duong',
    type: 'tinh',
    name_with_type: 'Tỉnh Bình Dương',
    code: '74',
  },
  { 
    id: 29,
    name: 'Quảng Nam',
    slug: 'quang-nam',
    type: 'tinh',
    name_with_type: 'Tỉnh Quảng Nam',
    code: '49',
  },
  { 
    id: 30,
    name: 'Điện Biên',
    slug: 'dien-bien',
    type: 'tinh',
    name_with_type: 'Tỉnh Điện Biên',
    code: '11',
  },
  { 
    id: 31,
    name: 'Kon Tum',
    slug: 'kon-tum',
    type: 'tinh',
    name_with_type: 'Tỉnh Kon Tum',
    code: '62',
  },
  { 
    id: 32,
    name: 'Bạc Liêu',
    slug: 'bac-lieu',
    type: 'tinh',
    name_with_type: 'Tỉnh Bạc Liêu',
    code: '95',
  },
  { 
    id: 33,
    name: 'Đắk Lắk',
    slug: 'dak-lak',
    type: 'tinh',
    name_with_type: 'Tỉnh Đắk Lắk',
    code: '66',
  },
  { 
    id: 34,
    name: 'An Giang',
    slug: 'an-giang',
    type: 'tinh',
    name_with_type: 'Tỉnh An Giang',
    code: '89',
  },
  { 
    id: 35,
    name: 'Thanh Hóa',
    slug: 'thanh-hoa',
    type: 'tinh',
    name_with_type: 'Tỉnh Thanh Hóa',
    code: '38',
  },
  { 
    id: 36,
    name: 'Quảng Ngãi',
    slug: 'quang-ngai',
    type: 'tinh',
    name_with_type: 'Tỉnh Quảng Ngãi',
    code: '51',
  },
  { 
    id: 37,
    name: 'Tây Ninh',
    slug: 'tay-ninh',
    type: 'tinh',
    name_with_type: 'Tỉnh Tây Ninh',
    code: '72',
  },
  { 
    id: 38,
    name: 'Bắc Giang',
    slug: 'bac-giang',
    type: 'tinh',
    name_with_type: 'Tỉnh Bắc Giang',
    code: '24',
  },

  { 
    id: 39,
    name: 'Ninh Thuận',
    slug: 'ninh-thuan',
    type: 'tinh',
    name_with_type: 'Tỉnh Ninh Thuận',
    code: '58',
  },
{ 
  id: 40,
    name: 'Tuyên Quang',
    slug: 'tuyen-quang',
    type: 'tinh',
    name_with_type: 'Tỉnh Tuyên Quang',
    code: '08',
  },
  { 
    id: 41,
    name: 'Sơn La',
    slug: 'son-la',
    type: 'tinh',
    name_with_type: 'Tỉnh Sơn La',
    code: '14',
  },
  { 
    id: 42,
    name: 'Nam Định',
    slug: 'nam-dinh',
    type: 'tinh',
    name_with_type: 'Tỉnh Nam Định',
    code: '36',
  },
  { 
    id: 43,
    name: 'Hà Nam',
    slug: 'ha-nam',
    type: 'tinh',
    name_with_type: 'Tỉnh Hà Nam',
    code: '35',
  },
  { 
    id: 44,
    name: 'Hải Dương',
    slug: 'hai-duong',
    type: 'tinh',
    name_with_type: 'Tỉnh Hải Dương',
    code: '30',
  },
  { 
    id: 45,
    name: 'Bà Rịa - Vũng Tàu',
    slug: 'ba-ria-vung-tau',
    type: 'tinh',
    name_with_type: 'Tỉnh Bà Rịa - Vũng Tàu',
    code: '77',
  },
  { 
    id: 46,
    name: 'Kiên Giang',
    slug: 'kien-giang',
    type: 'tinh',
    name_with_type: 'Tỉnh Kiên Giang',
    code: '91',
  },
{ 
  id: 47,
    name: 'Cao Bằng',
    slug: 'cao-bang',
    type: 'tinh',
    name_with_type: 'Tỉnh Cao Bằng',
    code: '4',
  },
  { 
    id: 48,
    name: 'Hà Tĩnh',
    slug: 'ha-tinh',
    type: 'tinh',
    name_with_type: 'Tỉnh Hà Tĩnh',
    code: '42',
  },
  { 
    id: 49,
    name: 'Gia Lai',
    slug: 'gia-lai',
    type: 'tinh',
    name_with_type: 'Tỉnh Gia Lai',
    code: '64',
  },
  { 
    id: 50,
    name: 'Hoà Bình',
    slug: 'hoa-binh',
    type: 'tinh',
    name_with_type: 'Tỉnh Hoà Bình',
    code: '17',
  },
  { 
    id: 51,
    name: 'Sóc Trăng',
    slug: 'soc-trang',
    type: 'tinh',
    name_with_type: 'Tỉnh Sóc Trăng',
    code: '94',
  },
  { 
    id: 52,
    name: 'Bình Định',
    slug: 'binh-dinh',
    type: 'tinh',
    name_with_type: 'Tỉnh Bình Định',
    code: '52',
  },
  { 
    id: 53,
    name: 'Thái Bình',
    slug: 'thai-binh',
    type: 'tinh',
    name_with_type: 'Tỉnh Thái Bình',
    code: '34',
  },
  { 
    id: 54,
    name: 'Phú Thọ',
    slug: 'phu-tho',
    type: 'tinh',
    name_with_type: 'Tỉnh Phú Thọ',
    code: '25',
  },
  { 
    id: 55,
    name: 'Hậu Giang',
    slug: 'hau-giang',
    type: 'tinh',
    name_with_type: 'Tỉnh Hậu Giang',
    code: '93',
  },
  { 
    id: 56,
    name: 'Cần Thơ',
    slug: 'can-tho',
    type: 'thanh-pho',
    name_with_type: 'Thành phố Cần Thơ',
    code: '92',
  },
  { 
    id: 57,
    name: 'Quảng Ninh',
    slug: 'quang-ninh',
    type: 'tinh',
    name_with_type: 'Tỉnh Quảng Ninh',
    code: '22',
  },
  { 
    id: 58,
    name: 'Quảng Trị',
    slug: 'quang-tri',
    type: 'tinh',
    name_with_type: 'Tỉnh Quảng Trị',
    code: '45',
  },
  { 
    id: 59,
    name: 'Lào Cai',
    slug: 'lao-cai',
    type: 'tinh',
    name_with_type: 'Tỉnh Lào Cai',
    code: '10',
  },
  { 
    id: 60,
    name: 'Đắk Nông',
    slug: 'dak-nong',
    type: 'tinh',
    name_with_type: 'Tỉnh Đắk Nông',
    code: '67',
  },
  { 
    id: 61,
    name: 'Bắc Ninh',
    slug: 'bac-ninh',
    type: 'tinh',
    name_with_type: 'Tỉnh Bắc Ninh',
    code: '27',
  },
  { 
    id: 62,
    name: 'Lâm Đồng',
    slug: 'lam-dong',
    type: 'tinh',
    name_with_type: 'Tỉnh Lâm Đồng',
    code: '68',
  },
  { 
    id: 63,
    name: 'Thái Nguyên',
    slug: 'thai-nguyen',
    type: 'tinh',
    name_with_type: 'Tỉnh Thái Nguyên',
    code: '19',
  },
  { 
    id: 64,
    name: 'Bình Thuận',
    slug: 'binh-thuan',
    type: 'tinh',
    name_with_type: 'Tỉnh Bình Thuận',
    code: '60',
  },
  { 
    id: 65,
    name: 'Khánh Hòa',
    slug: 'khanh-hoa',
    type: 'tinh',
    name_with_type: 'Tỉnh Khánh Hòa',
    code: '56',
  },
  { 
    id: 66,
    name: 'Bến Tre',
    slug: 'ben-tre',
    type: 'tinh',
    name_with_type: 'Tỉnh Bến Tre',
    code: '83',
  },
  { 
    id: 67,
    name: 'Thừa Thiên Huế',
    slug: 'thua-thien-hue',
    type: 'tinh',
    name_with_type: 'Tỉnh Thừa Thiên Huế',
    code: '46',
  },
{ 
  id: 68,
    name: 'Hà Giang',
    slug: 'ha-giang',
    type: 'tinh',
    name_with_type: 'Tỉnh Hà Giang',
    code: '2',
  },
  { 
    id: 69,
    name: 'Trà Vinh',
    slug: 'tra-vinh',
    type: 'tinh',
    name_with_type: 'Tỉnh Trà Vinh',
    code: '84',
  },
  { 
    id: 70,
    name: 'Long An',
    slug: 'long-an',
    type: 'tinh',
    name_with_type: 'Tỉnh Long An',
    code: '80',
  },
{ 
  id: 71,
    name: 'Bắc Kạn',
    slug: 'bac-kan',
    type: 'tinh',
    name_with_type: 'Tỉnh Bắc Kạn',
    code: '6',
  },
  { 
    id: 72,
    name: 'Đà Nẵng',
    slug: 'da-nang',
    type: 'thanh-pho',
    name_with_type: 'Thành phố Đà Nẵng',
    code: '48',
  },
  { 
    id: 73,
    name: 'Bình Phước',
    slug: 'binh-phuoc',
    type: 'tinh',
    name_with_type: 'Tỉnh Bình Phước',
    code: '70',
  },
]

export const EXP = [
  {
    id: 101,
    name: 'từ 6 tháng đến 1 năm',
    slug: '6-thang',
  },
  {
    id: 102,
    name: '2 năm',
    slug: '2-nam',
  },
  {
    id: 103,
    name: '3 năm',
    slug: '3-nam',
  },
  {
    id: 104,
    name: '4 năm',
    slug: '4-nam',
  },
  {
    id: 105,
    name: '5 năm',
    slug: '5-nam',
  },
  {
    id: 106,
    name: '6 năm',
    slug: '6-nam',
  },
  {
    id: 107,
    name: '7 năm',
    slug: '7-nam',
  },
  {
    id: 108,
    name: '8 năm',
    slug: '8-nam',
  },
  {
    id: 109,
    name: '9 năm',
    slug: '9-nam',
  },
  {
    id: 110,
    name: '10 năm',
    slug: '10-nam',
  },

]

export const EDUCATION = [
  {
    id: 111,
    name: 'Chứng Chỉ',
    slug: 'chung-chi',
  },
  {
    id: 112,
    name: 'Cao Đẳng',
    slug: 'cao-dang',
  },
  {
    id: 113,
    name: 'Đại Học',
    slug: 'dai-hoc',
  },
  {
    id: 114,
    name: 'Cao Học',
    slug: 'cao-hoc',
  },
]

export const RANK = [
  {
    id: 115,
    name: 'Junior',
    slug: 'so-cap',
  },
  {
    id: 116,
    name: 'Senior',
    slug: 'lau-nam',
  },
  {
    id: 117,
    name: 'Architect',
    slug: 'quan-ly',
  },
  {
    id: 118,
    name: 'Mid-lever Manager',
    slug: 'quan-ly-trung-cap',
  },
  {
    id: 119,
    name: 'Senior Leader',
    slug: 'quan-ly-cao-cap',
  },
]

export const WORK = [
  {
    id: 120,
    name: 'Onsite',
    slug: 'viec-lam',
  },
]

export const STATUS = [
  {
    id: 121,
    name: 'Pending',
    value: 'pending',
  },
  {
    id: 122,
    name: 'Wait',
    value: 'wait',
  },
  {
    id: 123,
    name: 'Active',
    value: 'active',
  },
  {
    id: 124,
    name: 'Deactive',
    value: 'deactive',
  },
  {
    id: 125,
    name: 'Suspended',
    value: 'suspended',
  }
]

export const SEARCHNUMBER = [
  {
    id: '5',
    label: '5',
  },
  {
    id: '10',
    label: '10',
  },
  {
    id: '15',
    label: '15',
  },
  {
    id: '20',
    label: '20',
  },
]

export const STATUSPOST = [
  {
    id: 126,
    name: 'Active',
    value: 'active',
  },
  {
    id: 127,
    name: 'Deactive',
    value: 'deactive',
  },
]